
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
      - redis
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      REDIS_HOST: redis
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0 # or your desired version
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  redis:
    image: redis:latest # or your desired version
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  esdata:
  redisdata: