"""Initialisation des tables

Revision ID: 09e22f28d7a2
Revises: 
Create Date: 2025-04-13 20:38:47.426615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09e22f28d7a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donnees')
    with op.batch_alter_table('donnees_modalites', schema=None) as batch_op:
        batch_op.drop_index('unique_donnee_modalite')

    op.drop_table('donnees_modalites')
    op.drop_table('dimensions')
    op.drop_table('v1_indicateur')
    op.drop_table('niveaudesagre')
    op.drop_table('indicateurs')
    op.drop_table('modalites')
    op.drop_table('domaines')
    op.drop_table('annees')
    op.drop_table('sous_domaines')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sous_domaines',
    sa.Column('idSousDomaines', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('f_idDomaines', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('nomSousDomaines', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['f_idDomaines'], ['domaines.idDomaines'], name='sous_domaines_ibfk_1'),
    sa.PrimaryKeyConstraint('idSousDomaines'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('annees',
    sa.Column('idAnnees', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('valAnnees', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idAnnees'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('domaines',
    sa.Column('idDomaines', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('nomDomaines', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('idDomaines'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('modalites',
    sa.Column('idModalites', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('f_idDimensions', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('nomModalites', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['f_idDimensions'], ['dimensions.idDimensions'], name='modalites_ibfk_1'),
    sa.PrimaryKeyConstraint('idModalites'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('indicateurs',
    sa.Column('idIndicateurs', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('f_idSousDomaines', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('nomIndicateur', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('definition', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['f_idSousDomaines'], ['sous_domaines.idSousDomaines'], name='indicateurs_ibfk_1'),
    sa.PrimaryKeyConstraint('idIndicateurs'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('niveaudesagre',
    sa.Column('idNiveauDesagre', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('f_idIndicateurs', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('nomNiveauDesagre', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['f_idIndicateurs'], ['indicateurs.idIndicateurs'], name='niveaudesagre_ibfk_1'),
    sa.PrimaryKeyConstraint('idNiveauDesagre'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('v1_indicateur',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('valeur', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dimensions',
    sa.Column('idDimensions', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('nomDimension', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('idDimensions'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('donnees_modalites',
    sa.Column('idDonnees_modalites', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('f_idDonnees', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_idModalites', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['f_idDonnees'], ['donnees.idDonnees'], name='donnees_modalites_ibfk_1'),
    sa.ForeignKeyConstraint(['f_idModalites'], ['modalites.idModalites'], name='donnees_modalites_ibfk_2'),
    sa.PrimaryKeyConstraint('idDonnees_modalites'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('donnees_modalites', schema=None) as batch_op:
        batch_op.create_index('unique_donnee_modalite', ['f_idDonnees', 'f_idModalites'], unique=True)

    op.create_table('donnees',
    sa.Column('idDonnees', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('f_idIndicateurs', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('f_idAnnees', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('valDonnees', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['f_idAnnees'], ['annees.idAnnees'], name='donnees_ibfk_2'),
    sa.ForeignKeyConstraint(['f_idIndicateurs'], ['indicateurs.idIndicateurs'], name='donnees_ibfk_1'),
    sa.PrimaryKeyConstraint('idDonnees'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
