"""empty message

Revision ID: 45d9586d05c6
Revises: 
Create Date: 2025-03-17 18:25:26.791118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45d9586d05c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Maladies_du_PEV')
    op.drop_table('Niveau_Superieur')
    op.drop_table('Sexe')
    op.drop_table('NiveauDesagregation')
    op.drop_table('GroupeAge')
    op.drop_table('Niveau_Professionnel')
    op.drop_table('Trimestre')
    op.drop_table('Type_de_groupes_culturels')
    op.drop_table('Region')
    op.drop_table('Infection_respiratoire')
    op.drop_table('Directeur')
    op.drop_table('Type_infrastructures_ou_organisations_sportives')
    op.drop_table('Pathologie')
    op.drop_table('Domaine')
    op.drop_table('Type_actions_culturelles_et_artistiques')
    op.drop_table('ValeurIndicateur2')
    op.drop_table('Type_de_manifestations_culturelles')
    op.drop_table('Niveau_Prescolaire')
    op.drop_table('Type_de_Patrimoines_culturels_immatériels')
    op.drop_table('Type_de_vulnerabilite')
    op.drop_table('Niveau_Technique')
    op.drop_table('indicateur_valeur_libelle_propre')
    op.drop_table('Disciplines_sportives')
    op.drop_table('Type_suivi')
    op.drop_table('Service_Medicaux')
    op.drop_table('Niveau_Secondaire_2nd_cycle')
    op.drop_table('valeur_indicateur_libelle')
    op.drop_table('ValeursIndicateurs')
    op.drop_table('Type_de_Maladie')
    op.drop_table('Maladies_infectieuses')
    with op.batch_alter_table('Administrateur', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('Administrateur')
    with op.batch_alter_table('V1_indicateur', schema=None) as batch_op:
        batch_op.drop_index('id_UNIQUE')

    op.drop_table('V1_indicateur')
    op.drop_table('valeur_indicateur_libelle_ok')
    op.drop_table('indicateur_v2')
    op.drop_table('Maladies_IST')
    op.drop_table('niveau_desagregation')
    op.drop_table('Etat_des_ouvrages')
    op.drop_table('Departement')
    op.drop_table('Type_abonnement')
    op.drop_table('Age')
    op.drop_table('Niveau_Primaire')
    op.drop_table('Types_de_vaccination')
    op.drop_table('Tranche_age')
    op.drop_table('indicateur_valeur_propre')
    op.drop_table('Type_examen')
    op.drop_table('Indicateur')
    op.drop_table('DirectionStatistique')
    op.drop_table('Type_infrastructures_culturelles')
    with op.batch_alter_table('Agent', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('Agent')
    op.drop_table('Etat_vaccinal')
    op.drop_table('Cycle')
    op.drop_table('Type_operateurs_des_oeuvres_esprit')
    op.drop_table('Type_de_prise_charge')
    op.drop_table('Infrastructures_sanitaires')
    op.drop_table('SousPrefectures')
    op.drop_table('Niveau_Secondaire_1er_cycle')
    op.drop_table('Activites_IEC')
    op.drop_table('Lieu_accouchement')
    with op.batch_alter_table('Superviseur', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('Superviseur')
    op.drop_table('valeur_rejet')
    op.drop_table('SousDomaine')
    op.drop_table('Niveau')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Niveau',
    sa.Column('id_niveau', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_niveau', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_niveau'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('SousDomaine',
    sa.Column('sous_domaine_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('f_domaine_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nom_sous_domaine', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['f_domaine_id'], ['Domaine.domaine_id'], name='sousdomaine_ibfk_1'),
    sa.PrimaryKeyConstraint('sous_domaine_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('valeur_rejet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_region', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_departement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_sousprefecture', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_indicateur', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Valeur', mysql.FLOAT(), nullable=True),
    sa.Column('Annee', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sexe', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('groupe_age', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nom_cycle', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_prescolaire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_primaire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_secondaire_1er_cycle', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_secondaire_2nd_cycle', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_technique', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_superieur', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_professionnel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_examen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_infrastructures_sanitaires', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_lieu_accouchement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_etat_vaccinal', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_types_de_vaccination', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_pathologie', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_tranche_age', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_maladies_du_pev', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_maladies_infectieuses', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_infectieuses_respiratoire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_maladies_ist', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_de_maladie', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_activites_iec', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_service_medicaux', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_infrastructures_sportives', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_disciplines_sportives', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_infrastructures_culturelles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_patrimoines_culturels_immatériels', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_actions_culturelles_artistiques', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_operateurs_oeuvres_esprit', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_groupes_culturels', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_manifestations_culturelles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_trimestre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('nom_etat_des_ouvrages', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_abonnnement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_suivi', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_de_vulnerabilite', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_de_prise_charge', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_niveau', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('statut', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('commentaires', mysql.TEXT(), nullable=True),
    sa.Column('date_rejet', sa.DATE(), nullable=True),
    sa.Column('Agent', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Superviseur',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_direction_statistique', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), server_default=sa.text("'superviseur'"), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_direction_statistique'], ['DirectionStatistique.id'], name='superviseur_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Superviseur', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('Lieu_accouchement',
    sa.Column('id_lieu_accouchement', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_lieu_accouchement', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_lieu_accouchement'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Activites_IEC',
    sa.Column('id_activites_iec', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_activites_iec', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_activites_iec'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Niveau_Secondaire_1er_cycle',
    sa.Column('niv_secondaire_1er_cycle_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_secondaire_1er_cycle', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('niv_secondaire_1er_cycle_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('SousPrefectures',
    sa.Column('sousprefect_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('f_departement_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nom_sousprefecture', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['f_departement_id'], ['Departement.departement_id'], name='sousprefectures_ibfk_1'),
    sa.PrimaryKeyConstraint('sousprefect_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Infrastructures_sanitaires',
    sa.Column('id_infrastructures_sanitaires', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_infrastructures_sanitaires', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_infrastructures_sanitaires'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_de_prise_charge',
    sa.Column('id_type_de_prise_charge', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_de_prise_charge', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_de_prise_charge'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_operateurs_des_oeuvres_esprit',
    sa.Column('id_type_operateurs_oeuvres_esprit', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_operateurs_oeuvres_esprit', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_operateurs_oeuvres_esprit'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Cycle',
    sa.Column('id_cycle', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_cycle', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_cycle'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Etat_vaccinal',
    sa.Column('id_etat_vaccinal', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_etat_vaccinal', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_etat_vaccinal'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Agent',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_sup', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), server_default=sa.text("'agent'"), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_sup'], ['Superviseur.id'], name='agent_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Agent', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('Type_infrastructures_culturelles',
    sa.Column('id_type_infrastructures_culturelles', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_infrastructures_culturelles', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_infrastructures_culturelles'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('DirectionStatistique',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Indicateur',
    sa.Column('indicateur_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('f_domaine_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nom_indicateur', mysql.TEXT(), nullable=True),
    sa.Column('definition', mysql.LONGTEXT(), nullable=True),
    sa.Column('mode_calcul', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['f_domaine_id'], ['Domaine.domaine_id'], name='indicateur_ibfk_1'),
    sa.PrimaryKeyConstraint('indicateur_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_examen',
    sa.Column('id_type_examen', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_examen', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_examen'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('indicateur_valeur_propre',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Indicateur', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('valeur', mysql.FLOAT(), nullable=True),
    sa.Column('annee', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Region', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Departement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Sous_prefecture', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Groupe_ages', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Ages', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_centre_etat_civil', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Source_donnees_admnistratives', mysql.TEXT(), nullable=True),
    sa.Column('Delai_Declaration', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Statut_decision', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_consentement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Statut', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Cycle', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Niveau_Prescolaire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Niveau_Primaire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Niveau_Secondaire_1er_cycle', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Niveau_Secondaire_2nd_cycle', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Niveau_Technique', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Niveau_Superieur', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Niveau_Professionnel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_examen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Commodites', mysql.TEXT(), nullable=True),
    sa.Column('Categorie_enseignants_publics', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Categorie_enseignants_prives', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Grade_enseignants_primaire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Groupe_Ages_scar_pr', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Lieu_accouchement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Etat_vaccinal', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Types_vaccination', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Pathologie', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Tranche_age', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Maladies_du_PEV', mysql.TEXT(), nullable=True),
    sa.Column('Maladies_infectieuses', mysql.TEXT(), nullable=True),
    sa.Column('Infections_respiratoire_aigue', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Maladies_IST', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_Maladie', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Activites_IEC', mysql.TEXT(), nullable=True),
    sa.Column('Service_Medicaux', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Types_infrastructures_prives', mysql.TEXT(), nullable=True),
    sa.Column('Types_infrastructures_publiques', mysql.TEXT(), nullable=True),
    sa.Column('Type_medecin', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Types_suivi', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Types_vulnerabilites', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Types_prises_en_charge', mysql.TEXT(), nullable=True),
    sa.Column('Niveau', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_Prestations', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Trimestre', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_infrastructures_organisations_sportives', mysql.TEXT(), nullable=True),
    sa.Column('Disciplines_sportives', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_infrastructures_culturelles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_Patrimoines_culturels', mysql.TEXT(), nullable=True),
    sa.Column('Type_Patrimoines_culturels_immateriels', mysql.TEXT(), nullable=True),
    sa.Column('Type_actions_culturelles_artistiques', mysql.TEXT(), nullable=True),
    sa.Column('Type_operateurs_oeuvres_esprit', mysql.TEXT(), nullable=True),
    sa.Column('Type_groupes_culturels', mysql.TEXT(), nullable=True),
    sa.Column('Type_manifestations_culturelles', mysql.TEXT(), nullable=True),
    sa.Column('Type_culture_exportation', mysql.TEXT(), nullable=True),
    sa.Column('Type_culture_vivriere', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_culture_maraichere', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_produit_agricole_rente', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_produit_vivrier', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Especes', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_animal', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Type_Peche', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Produits', mysql.TEXT(), nullable=True),
    sa.Column('Type_projets_realises', mysql.TEXT(), nullable=True),
    sa.Column('Type_poissons', mysql.TEXT(), nullable=True),
    sa.Column('Type_produits_miniers', mysql.TEXT(), nullable=True),
    sa.Column('Type_mineraies', mysql.TEXT(), nullable=True),
    sa.Column('Type_produits_petroliers', mysql.TEXT(), nullable=True),
    sa.Column('Type_stations', mysql.TEXT(), nullable=True),
    sa.Column('Etat_ouvrages', mysql.TEXT(), nullable=True),
    sa.Column('Type_ouvrages', mysql.TEXT(), nullable=True),
    sa.Column('Type_abonnement', mysql.TEXT(), nullable=True),
    sa.Column('Types_vehicules', mysql.TEXT(), nullable=True),
    sa.Column('Categories_permis', mysql.TEXT(), nullable=True),
    sa.Column('Type_vehicules_marchandises', mysql.TEXT(), nullable=True),
    sa.Column('Type_vehicules_passagers', mysql.TEXT(), nullable=True),
    sa.Column('Categories_routes', mysql.TEXT(), nullable=True),
    sa.Column('Compagnies_transport', mysql.TEXT(), nullable=True),
    sa.Column('Type_transport', mysql.TEXT(), nullable=True),
    sa.Column('Type_abonnes', mysql.TEXT(), nullable=True),
    sa.Column('Nature_mandat', mysql.TEXT(), nullable=True),
    sa.Column('Nature_juridique', mysql.TEXT(), nullable=True),
    sa.Column('Nationalite', mysql.TEXT(), nullable=True),
    sa.Column('Secteur_activites', mysql.TEXT(), nullable=True),
    sa.Column('Collectivites_territoriales', mysql.TEXT(), nullable=True),
    sa.Column('Secteurs_activite', mysql.TEXT(), nullable=True),
    sa.Column('Regime_imposition', mysql.TEXT(), nullable=True),
    sa.Column('Forme_juridique', mysql.TEXT(), nullable=True),
    sa.Column('Type_impots', mysql.TEXT(), nullable=True),
    sa.Column('Type_nationalite', mysql.TEXT(), nullable=True),
    sa.Column('Secteurs_activite_2', mysql.TEXT(), nullable=True),
    sa.Column('Types_infrastructures_production_aquacoles', mysql.TEXT(), nullable=True),
    sa.Column('Types_especes_eleves', mysql.TEXT(), nullable=True),
    sa.Column('Produits_petrolier', mysql.TEXT(), nullable=True),
    sa.Column('Domaines', mysql.TEXT(), nullable=True),
    sa.Column('Especes_2', mysql.TEXT(), nullable=True),
    sa.Column('Mois', mysql.TEXT(), nullable=True),
    sa.Column('Directions_regionales_ministeres', mysql.TEXT(), nullable=True),
    sa.Column('Milieu_residence', mysql.TEXT(), nullable=True),
    sa.Column('Situation_emploi', mysql.TEXT(), nullable=True),
    sa.Column('Branche_activites', mysql.TEXT(), nullable=True),
    sa.Column('Secteur_activites_chomage_technique', mysql.TEXT(), nullable=True),
    sa.Column('Categories', mysql.TEXT(), nullable=True),
    sa.Column('Secteur_activites_licenciement_collectif', mysql.TEXT(), nullable=True),
    sa.Column('Projets_realises', mysql.TEXT(), nullable=True),
    sa.Column('Mois_2', mysql.TEXT(), nullable=True),
    sa.Column('Groupe_ages_2', mysql.TEXT(), nullable=True),
    sa.Column('Type_violence', mysql.TEXT(), nullable=True),
    sa.Column('Activites_prevention_VBG', mysql.TEXT(), nullable=True),
    sa.Column('Activites_prevention_enfants', mysql.TEXT(), nullable=True),
    sa.Column('Type_violence_protection_enfance', mysql.TEXT(), nullable=True),
    sa.Column('Nature_services', mysql.TEXT(), nullable=True),
    sa.Column('Niveau_2', mysql.TEXT(), nullable=True),
    sa.Column('Types_sorties_interventions', mysql.TEXT(), nullable=True),
    sa.Column('Types_victimes', mysql.TEXT(), nullable=True),
    sa.Column('Types_moyens_extinction', mysql.TEXT(), nullable=True),
    sa.Column('Type_juridiction', mysql.TEXT(), nullable=True),
    sa.Column('Nature_affaires', mysql.TEXT(), nullable=True),
    sa.Column('Type_Criminalites', mysql.TEXT(), nullable=True),
    sa.Column('Type_infractions', mysql.TEXT(), nullable=True),
    sa.Column('Type_infractions_biens', mysql.TEXT(), nullable=True),
    sa.Column('Type_infractions_moeurs', mysql.TEXT(), nullable=True),
    sa.Column('Type_infractions_autre', mysql.TEXT(), nullable=True),
    sa.Column('Type_affaire', mysql.TEXT(), nullable=True),
    sa.Column('Parti_politique', mysql.TEXT(), nullable=True),
    sa.Column('Sexe', mysql.TEXT(), nullable=True),
    sa.Column('Mairies', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Tranche_age',
    sa.Column('id_tranche_age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_tranche_age', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_tranche_age'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Types_de_vaccination',
    sa.Column('id_types_de_vaccination', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_types_de_vaccination', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_types_de_vaccination'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Niveau_Primaire',
    sa.Column('niv_primaire_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_primaire', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('niv_primaire_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Age',
    sa.Column('age_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('age_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_abonnement',
    sa.Column('id_type_abonnement', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_abonnement', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_abonnement'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Departement',
    sa.Column('departement_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('f_region_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nom_departement', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['f_region_id'], ['Region.region_id'], name='departement_ibfk_1'),
    sa.PrimaryKeyConstraint('departement_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Etat_des_ouvrages',
    sa.Column('id_etat_des_ouvrages', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_etat_des_ouvrages', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_etat_des_ouvrages'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('niveau_desagregation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_niveau_desagregation', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Maladies_IST',
    sa.Column('id_maladies_ist', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_maladies_ist', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_maladies_ist'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('indicateur_v2',
    sa.Column('indicateur_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('indicateur', mysql.TEXT(), nullable=True),
    sa.Column('definitions', mysql.LONGTEXT(), nullable=True),
    sa.Column('mode_calcul', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('indicateur_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('valeur_indicateur_libelle_ok',
    sa.Column('id', mysql.VARCHAR(length=55), nullable=False),
    sa.Column('region', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('departement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sousprefecture', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('indicateur', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('valeur', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('annee', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sexe', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('groupe_age', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('age', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('statut_scolaire', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('cycle_scolaire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('prescolaire', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('primaire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('secondaire_1er_cycle', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('secondaire_2nd_cycle', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('technique', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('superieur', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('professionnel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_examen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('infrastructures_sanitaires', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lieu_accouchement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('etat_vaccinal', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('types_de_vaccination', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pathologie', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tranche_age', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('maladies_du_pev', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('maladies_infectieuses', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('infectieuses_respiratoire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('maladies_ist', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_de_maladie', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('activites_iec', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('service_medicaux', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_infrastructures_sportives', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('disciplines_sportives', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_infrastructures_culturelles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_patrimoines_culturels_immatériels', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_actions_culturelles_artistiques', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_operateurs_oeuvres_esprit', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_groupes_culturels', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_manifestations_culturelles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('trimestre', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('etat_des_ouvrages', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_abonnement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_suivi', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_de_vulnerabilite', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_de_prise_charge', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('niveau', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('statut_approbation', mysql.VARCHAR(length=20), server_default=sa.text("'Non approuvé'"), nullable=True),
    sa.Column('commentaires', mysql.TEXT(), nullable=True),
    sa.Column('date_rejet', mysql.DATETIME(), nullable=True),
    sa.Column('Agent', mysql.TEXT(), nullable=True),
    sa.Column('sousdomaines', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('domaine', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('definition', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('V1_indicateur',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Dimension', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Modalites', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Indicateurs', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Annee', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('Valeur', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Region', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('V1_indicateur', schema=None) as batch_op:
        batch_op.create_index('id_UNIQUE', ['id'], unique=True)

    op.create_table('Administrateur',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), server_default=sa.text("'administrateur'"), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Administrateur', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('Maladies_infectieuses',
    sa.Column('id_maladies_infectieuses', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_maladies_infectieuses', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_maladies_infectieuses'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_de_Maladie',
    sa.Column('id_type_de_maladie', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_de_maladie', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_de_maladie'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ValeursIndicateurs',
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Valeur', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Annee', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_sexe_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_grp_age_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_age_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_cycle_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_region_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_departement_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_sous_prefecture_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_indicateur_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_niveau_prescolaire_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_niveau_primaire_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_niveau_secondaire_1er_cycle_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_niveau_secondaire_2nd_cycle_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_niveau_technique_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_niveau_superieur_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_niveau_professionnel_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_examen_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_infrastructures_sanitaires_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_lieu_accouchement_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_etat_vaccinal_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_types_de_vaccination_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_pathologie_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_tranche_age_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_maladies_du_pev_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_maladies_infectieuses_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_infectieuses_respiratoire_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_maladies_ist_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_de_maladie_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_activites_iec_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_service_medicaux_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_infrastructures_ou_organisations_sportives_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_disciplines_sportives_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_infrastructures_culturelles_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_de_patrimoines_culturels_immat_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_actions_culturelles_et_artistiques_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_operateurs_des_oeuvres_esprit_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_de_groupes_culturels_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_de_manifestations_culturelles_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_trimestre_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_etat_des_ouvrages_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_abonnement_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_suivi_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_de_vulnerabilite_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_type_de_prise_charge_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('f_niveau_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['f_activites_iec_id'], ['Activites_IEC.id_activites_iec'], name='valeursindicateurs_ibfk_35'),
    sa.ForeignKeyConstraint(['f_age_id'], ['Age.age_id'], name='valeursindicateurs_ibfk_14'),
    sa.ForeignKeyConstraint(['f_cycle_id'], ['Cycle.id_cycle'], name='valeursindicateurs_ibfk_15'),
    sa.ForeignKeyConstraint(['f_departement_id'], ['Departement.departement_id'], name='valeursindicateurs_ibfk_9'),
    sa.ForeignKeyConstraint(['f_disciplines_sportives_id'], ['Disciplines_sportives.id_disciplines_sportives'], name='valeursindicateurs_ibfk_38'),
    sa.ForeignKeyConstraint(['f_etat_des_ouvrages_id'], ['Etat_des_ouvrages.id_etat_des_ouvrages'], name='valeursindicateurs_ibfk_2'),
    sa.ForeignKeyConstraint(['f_etat_vaccinal_id'], ['Etat_vaccinal.id_etat_vaccinal'], name='valeursindicateurs_ibfk_26'),
    sa.ForeignKeyConstraint(['f_grp_age_id'], ['GroupeAge.grp_age_id'], name='valeursindicateurs_ibfk_13'),
    sa.ForeignKeyConstraint(['f_indicateur_id'], ['Indicateur.indicateur_id'], name='valeursindicateurs_ibfk_11'),
    sa.ForeignKeyConstraint(['f_infectieuses_respiratoire_id'], ['Infection_respiratoire.id_infectieuses_respiratoire'], name='valeursindicateurs_ibfk_32'),
    sa.ForeignKeyConstraint(['f_infrastructures_sanitaires_id'], ['Infrastructures_sanitaires.id_infrastructures_sanitaires'], name='valeursindicateurs_ibfk_24'),
    sa.ForeignKeyConstraint(['f_lieu_accouchement_id'], ['Lieu_accouchement.id_lieu_accouchement'], name='valeursindicateurs_ibfk_25'),
    sa.ForeignKeyConstraint(['f_maladies_du_pev_id'], ['Maladies_du_PEV.id_maladies_du_pev'], name='valeursindicateurs_ibfk_30'),
    sa.ForeignKeyConstraint(['f_maladies_infectieuses_id'], ['Maladies_infectieuses.id_maladies_infectieuses'], name='valeursindicateurs_ibfk_31'),
    sa.ForeignKeyConstraint(['f_maladies_ist_id'], ['Maladies_IST.id_maladies_ist'], name='valeursindicateurs_ibfk_33'),
    sa.ForeignKeyConstraint(['f_niveau_id'], ['Niveau.id_niveau'], name='valeursindicateurs_ibfk_7'),
    sa.ForeignKeyConstraint(['f_niveau_prescolaire_id'], ['Niveau_Prescolaire.niv_prescolaire_id'], name='valeursindicateurs_ibfk_16'),
    sa.ForeignKeyConstraint(['f_niveau_primaire_id'], ['Niveau_Primaire.niv_primaire_id'], name='valeursindicateurs_ibfk_17'),
    sa.ForeignKeyConstraint(['f_niveau_professionnel_id'], ['Niveau_Professionnel.niv_professionnel_id'], name='valeursindicateurs_ibfk_22'),
    sa.ForeignKeyConstraint(['f_niveau_secondaire_1er_cycle_id'], ['Niveau_Secondaire_1er_cycle.niv_secondaire_1er_cycle_id'], name='valeursindicateurs_ibfk_18'),
    sa.ForeignKeyConstraint(['f_niveau_secondaire_2nd_cycle_id'], ['Niveau_Secondaire_2nd_cycle.niv_secondaire_2nd_cycle_id'], name='valeursindicateurs_ibfk_19'),
    sa.ForeignKeyConstraint(['f_niveau_superieur_id'], ['Niveau_Superieur.niv_superieur_id'], name='valeursindicateurs_ibfk_21'),
    sa.ForeignKeyConstraint(['f_niveau_technique_id'], ['Niveau_Technique.niv_technique_id'], name='valeursindicateurs_ibfk_20'),
    sa.ForeignKeyConstraint(['f_pathologie_id'], ['Pathologie.id_pathologie'], name='valeursindicateurs_ibfk_28'),
    sa.ForeignKeyConstraint(['f_region_id'], ['Region.region_id'], name='valeursindicateurs_ibfk_8'),
    sa.ForeignKeyConstraint(['f_service_medicaux_id'], ['Service_Medicaux.id_service_medicaux'], name='valeursindicateurs_ibfk_36'),
    sa.ForeignKeyConstraint(['f_sexe_id'], ['Sexe.sexe_id'], name='valeursindicateurs_ibfk_12'),
    sa.ForeignKeyConstraint(['f_sous_prefecture_id'], ['SousPrefectures.sousprefect_id'], name='valeursindicateurs_ibfk_10'),
    sa.ForeignKeyConstraint(['f_tranche_age_id'], ['Tranche_age.id_tranche_age'], name='valeursindicateurs_ibfk_29'),
    sa.ForeignKeyConstraint(['f_trimestre_id'], ['Trimestre.id_trimestre'], name='valeursindicateurs_ibfk_1'),
    sa.ForeignKeyConstraint(['f_type_abonnement_id'], ['Type_abonnement.id_type_abonnement'], name='valeursindicateurs_ibfk_3'),
    sa.ForeignKeyConstraint(['f_type_actions_culturelles_et_artistiques_id'], ['Type_actions_culturelles_et_artistiques.id_type_actions_culturelles_artistiques'], name='valeursindicateurs_ibfk_41'),
    sa.ForeignKeyConstraint(['f_type_de_groupes_culturels_id'], ['Type_de_groupes_culturels.id_type_groupes_culturels'], name='valeursindicateurs_ibfk_43'),
    sa.ForeignKeyConstraint(['f_type_de_maladie_id'], ['Type_de_Maladie.id_type_de_maladie'], name='valeursindicateurs_ibfk_34'),
    sa.ForeignKeyConstraint(['f_type_de_manifestations_culturelles_id'], ['Type_de_manifestations_culturelles.id_type_manifestations_culturelles'], name='valeursindicateurs_ibfk_44'),
    sa.ForeignKeyConstraint(['f_type_de_patrimoines_culturels_immat_id'], ['Type_de_Patrimoines_culturels_immatériels.id_type_patrimoines_culturels_immatériels'], name='valeursindicateurs_ibfk_40'),
    sa.ForeignKeyConstraint(['f_type_de_prise_charge_id'], ['Type_de_prise_charge.id_type_de_prise_charge'], name='valeursindicateurs_ibfk_6'),
    sa.ForeignKeyConstraint(['f_type_de_vulnerabilite_id'], ['Type_de_vulnerabilite.id_type_de_vulnerabilite'], name='valeursindicateurs_ibfk_5'),
    sa.ForeignKeyConstraint(['f_type_examen_id'], ['Type_examen.id_type_examen'], name='valeursindicateurs_ibfk_23'),
    sa.ForeignKeyConstraint(['f_type_infrastructures_culturelles_id'], ['Type_infrastructures_culturelles.id_type_infrastructures_culturelles'], name='valeursindicateurs_ibfk_39'),
    sa.ForeignKeyConstraint(['f_type_infrastructures_ou_organisations_sportives_id'], ['Type_infrastructures_ou_organisations_sportives.id_type_infrastructures_sportives'], name='valeursindicateurs_ibfk_37'),
    sa.ForeignKeyConstraint(['f_type_operateurs_des_oeuvres_esprit_id'], ['Type_operateurs_des_oeuvres_esprit.id_type_operateurs_oeuvres_esprit'], name='valeursindicateurs_ibfk_42'),
    sa.ForeignKeyConstraint(['f_type_suivi_id'], ['Type_suivi.id_type_suivi'], name='valeursindicateurs_ibfk_4'),
    sa.ForeignKeyConstraint(['f_types_de_vaccination_id'], ['Types_de_vaccination.id_types_de_vaccination'], name='valeursindicateurs_ibfk_27'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('valeur_indicateur_libelle',
    sa.Column('id', mysql.VARCHAR(length=55), nullable=False),
    sa.Column('nom_region', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_departement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_sousprefecture', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_indicateur', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Valeur', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Annee', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sexe', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('groupe_age', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nom_cycle', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_prescolaire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_primaire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_secondaire_1er_cycle', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_secondaire_2nd_cycle', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_technique', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_superieur', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_professionnel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_examen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_infrastructures_sanitaires', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_lieu_accouchement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_etat_vaccinal', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_types_de_vaccination', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_pathologie', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_tranche_age', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_maladies_du_pev', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_maladies_infectieuses', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_infectieuses_respiratoire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_maladies_ist', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_de_maladie', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_activites_iec', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_service_medicaux', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_infrastructures_sportives', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_disciplines_sportives', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_infrastructures_culturelles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_patrimoines_culturels_immatériels', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_actions_culturelles_artistiques', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_operateurs_oeuvres_esprit', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_groupes_culturels', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_manifestations_culturelles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_trimestre', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_etat_des_ouvrages', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_abonnement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_suivi', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_de_vulnerabilite', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_type_de_prise_charge', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_niveau', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('statut', mysql.VARCHAR(length=20), server_default=sa.text("'Non approuvé'"), nullable=True),
    sa.Column('commentaires', mysql.TEXT(), nullable=True),
    sa.Column('date_rejet', mysql.DATETIME(), nullable=True),
    sa.Column('Agent', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_collect', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Niveau_Secondaire_2nd_cycle',
    sa.Column('niv_secondaire_2nd_cycle_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_secondaire_2nd_cycle', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('niv_secondaire_2nd_cycle_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Service_Medicaux',
    sa.Column('id_service_medicaux', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_service_medicaux', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_service_medicaux'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_suivi',
    sa.Column('id_type_suivi', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_suivi', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_suivi'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Disciplines_sportives',
    sa.Column('id_disciplines_sportives', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_disciplines_sportives', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_disciplines_sportives'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('indicateur_valeur_libelle_propre',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Indicateur', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('valeur', mysql.FLOAT(), nullable=True),
    sa.Column('annee', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Region', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Departement', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Sous_prefecture', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Groupe_ages', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Ages', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('Type_centre_etat_civil', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Source_donnees_admnistratives', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Delai_Declaration', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Statut_decision', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_consentement', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Statut', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Cycle', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Niveau_Prescolaire', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Niveau_Primaire', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Niveau_Secondaire_1er_cycle', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Niveau_Secondaire_2nd_cycle', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Niveau_Technique', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Niveau_Superieur', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Niveau_Professionnel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_examen', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Commodites', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Categorie_enseignants_publics', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Categorie_enseignants_prives', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Grade_enseignants_primaire', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Groupe_Ages_scar_pr', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Lieu_accouchement', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Etat_vaccinal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Types_vaccination', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Pathologie', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Tranche_age', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Maladies_du_PEV', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Infections_respiratoire_aigue', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Maladies_IST', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_Maladie', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Activites_IEC', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Service_Medicaux', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Types_infrastructures_prives', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Types_infrastructures_publiques', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Types_suivi', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Types_vulnerabilites', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Types_prises_en_charge', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Niveau', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_Prestations', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Trimestre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_infrastructures_organisations_sportives', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Disciplines_sportives', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_infrastructures_culturelles', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_Patrimoines_culturels', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_Patrimoines_culturels_immateriels', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_actions_culturelles_artistiques', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_operateurs_oeuvres_esprit', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_groupes_culturels', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_manifestations_culturelles', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_culture_exportation', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_culture_vivriere', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_culture_maraichere', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_produit_agricole_rente', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_produit_vivrier', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Especes', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_animal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_Peche', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Produits', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_projets_realises', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_poissons', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_produits_miniers', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_mineraies', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_produits_petroliers', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_stations', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Etat_ouvrages', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_ouvrages', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_abonnement', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Types_vehicules', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Categories_permis', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_vehicules_marchandises', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_vehicules_passagers', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Categories_routes', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Compagnies_transport', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_transport', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_abonnes', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Categorie_hotels', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Nature_juridique', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Nationalite', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Secteur_activites', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Collectivites_territoriales', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Secteurs_activite', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Regime_imposition', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Forme_juridique', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_impots', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_nationalite', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Secteurs_activite_2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Types_infrastructures_production_aquacoles', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Types_especes_eleves', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Produits_petrolier', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Domaines', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Especes_2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Mois', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Directions_regionales_ministeres', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Milieu_residence', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Situation_emploi', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Branche_activites', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Secteur_activites_chomage_technique', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Categories', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Secteur_activites_licenciement_collectif', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Projets_realises', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Mois_2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Groupe_ages_2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_violence', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Activites_prevention_VBG', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Activites_prevention_enfants', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_violence_protection_enfance', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Nature_services', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Niveau_2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Types_sorties_interventions', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Types_victimes', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Types_moyens_extinction', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_juridiction', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Nature_affaires', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_Criminalites', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_infractions', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_infractions_biens', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_infractions_corporelle', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_infractions_moeurs', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_infractions_autre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Type_affaire', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Parti_politique', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Sexe', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('Mairies', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Niveau_Technique',
    sa.Column('niv_technique_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_technique', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('niv_technique_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_de_vulnerabilite',
    sa.Column('id_type_de_vulnerabilite', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_de_vulnerabilite', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_de_vulnerabilite'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_de_Patrimoines_culturels_immatériels',
    sa.Column('id_type_patrimoines_culturels_immatériels', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_patrimoines_culturels_immatériels', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_patrimoines_culturels_immatériels'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Niveau_Prescolaire',
    sa.Column('niv_prescolaire_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_prescolaire', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('niv_prescolaire_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_de_manifestations_culturelles',
    sa.Column('id_type_manifestations_culturelles', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_manifestations_culturelles', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_manifestations_culturelles'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ValeurIndicateur2',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('indicateur_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('desagregation_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valeur', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['desagregation_id'], ['NiveauDesagregation.id'], name='valeurindicateur2_ibfk_3'),
    sa.ForeignKeyConstraint(['indicateur_id'], ['Indicateur.indicateur_id'], name='valeurindicateur2_ibfk_2'),
    sa.ForeignKeyConstraint(['region_id'], ['Region.region_id'], name='valeurindicateur2_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_actions_culturelles_et_artistiques',
    sa.Column('id_type_actions_culturelles_artistiques', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_actions_culturelles_artistiques', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_actions_culturelles_artistiques'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Domaine',
    sa.Column('domaine_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_domaine', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('domaine_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Pathologie',
    sa.Column('id_pathologie', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_pathologie', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_pathologie'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_infrastructures_ou_organisations_sportives',
    sa.Column('id_type_infrastructures_sportives', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_infrastructures_sportives', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_infrastructures_sportives'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Directeur',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Nom', mysql.TEXT(), nullable=True),
    sa.Column('Prenom', mysql.TEXT(), nullable=True),
    sa.Column('Email', mysql.TEXT(), nullable=True),
    sa.Column('Numero', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Infection_respiratoire',
    sa.Column('id_infectieuses_respiratoire', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_infectieuses_respiratoire', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_infectieuses_respiratoire'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Region',
    sa.Column('region_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('f_direction_stat_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nom_region', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['f_direction_stat_id'], ['DirectionStatistique.id'], name='region_ibfk_1'),
    sa.PrimaryKeyConstraint('region_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Type_de_groupes_culturels',
    sa.Column('id_type_groupes_culturels', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_type_groupes_culturels', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type_groupes_culturels'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Trimestre',
    sa.Column('id_trimestre', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_trimestre', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_trimestre'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Niveau_Professionnel',
    sa.Column('niv_professionnel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_professionnel', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('niv_professionnel_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('GroupeAge',
    sa.Column('grp_age_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('groupe_age', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('grp_age_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('NiveauDesagregation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Sexe',
    sa.Column('sexe_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sexe', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('sexe_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Niveau_Superieur',
    sa.Column('niv_superieur_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_superieur', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('niv_superieur_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Maladies_du_PEV',
    sa.Column('id_maladies_du_pev', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_maladies_du_pev', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_maladies_du_pev'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
